name: ubuntu-latest-icc-ci2

on:
  push:
    branches:
      - master
      - feature/**
      - improvement/**
      - bugfix/**

  pull_request:
    branches:
      - master
      - feature/**
      - improvement/**
      - bugfix/**

jobs:
  build_linux_cpp:
    if: >-
      ! contains(toJSON(github.event.commits.*.message), '[skip ci]') &&
      ! contains(toJSON(github.event.commits.*.message), '[skip github]')

    runs-on: ubuntu-20.04
    container: intel/oneapi-hpckit
    steps:

      - uses: actions/checkout@v2
      - name: install_git
        run: apt update && apt install -y git

      - name: CMake
        run: echo "/host_usr_local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: script/ci_install_deps.sh

      - name: Configure
        run: cmake -S test -B build -D CMAKE_BUILD_TYPE=Debug

      - name: Build
        run: cmake --build build -j ${{ steps.cores.outputs.count }}

      - name: Run
        working-directory: build
        run: ctest --output-on-failure -j ${{ steps.cores.outputs.count }}
