name: Build & Test - MSVC

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          cmake-version: '3.19.x'

      - name: Install dependencies
        run: script/ci_install_deps.sh

      - name: Configure
        run: cmake -S test -B build -D CMAKE_BUILD_TYPE=Debug

      - name: Build
        run: cmake --build build -j ${{ steps.cores.outputs.count }}

      - name: Run
        working-directory: build
        run: ctest --output-on-failure -j ${{ steps.cores.outputs.count }}
