name: win-latest-msvc-ci

on:
  push:
    branches:
      - master
      - feature/**
      - improvement/**
      - bugfix/**

  pull_request:
    branches:
      - master
      - feature/**
      - improvement/**
      - bugfix/**

jobs:
  ci:
    defaults:
      run:
        shell: bash
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        vs: ["Visual Studio 16 2019", "Visual Studio 17 2022"]
        build: [Debug, Release]
        platform: [Win32, x64]

    name: "${{matrix.vs}}:${{matrix.platform}}:${{matrix.build}}"
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: script/ci_install_deps.sh

      - name: Configure
        run: cmake -S test -B build -D CMAKE_BUILD_TYPE=${{ matrix.build }}

      - name: Build
        run: cmake --build build -j ${{ steps.cores.outputs.count }}

      - name: Run
        working-directory: build
        run: ctest -C Debug --output-on-failure -j ${{ steps.cores.outputs.count }}
